name: Build and Upload Jar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure git
        run: |
          git config --global am.keepcr true
          git config --global core.autocrlf false
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

      - name: Update upstream
        run: ./gradlew updateUpstream --stacktrace

      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace

      - name: Build Quests
        run: ./gradlew buildQuests --stacktrace

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: Quests-Folia
          path: Quests-Patched/dist/build/libs/Quests-*.jar
          if-no-files-found: error
